# Generated by Django 5.0.4 on 2025-06-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(max_length=25)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('DOB', models.CharField(max_length=25)),
                ('SelectMembershipPlan', models.CharField(max_length=50)),
                ('SelectTrainer', models.CharField(max_length=50)),
                ('Reference', models.CharField(max_length=50)),
                ('PaymentStatus', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('DueDate', models.DateTimeField(blank=True, null=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=25)),
                ('Phone', models.CharField(max_length=12)),
                ('Salary', models.IntegerField()),
            ],
        ),
    ]
