# Generated by Django 5.0.4 on 2025-06-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_enrollment_membershipplan_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='Address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
