# Generated by Django 5.0.4 on 2025-06-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='PhoneNumber',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
